export const cursosComNotas = [
  { "curso": "Administração", "nota_corte_estimada": 650 },
  { "curso": "Agronomia", "nota_corte_estimada": 640 },
  { "curso": "Arqueologia", "nota_corte_estimada": 620 },
  { "curso": "Arquitetura e Urbanismo", "nota_corte_estimada": 730 },
  { "curso": "Artes Cênicas", "nota_corte_estimada": 640 },
  { "curso": "Artes Visuais", "nota_corte_estimada": 635 },
  { "curso": "Astronomia", "nota_corte_estimada": 730 },
  { "curso": "Biblioteconomia", "nota_corte_estimada": 610 },
  { "curso": "Biomedicina", "nota_corte_estimada": 715 },
  { "curso": "Ciência da Computação", "nota_corte_estimada": 760 },
  { "curso": "Ciências Biológicas", "nota_corte_estimada": 670 },
  { "curso": "Ciências Contábeis", "nota_corte_estimada": 645 },
  { "curso": "Ciências Econômicas", "nota_corte_estimada": 680 },
  { "curso": "Ciências Sociais", "nota_corte_estimada": 620 },
  { "curso": "Cinema e Audiovisual", "nota_corte_estimada": 700 },
  { "curso": "Dança", "nota_corte_estimada": 600 },
  { "curso": "Design", "nota_corte_estimada": 690 },
  { "curso": "Design de Interiores", "nota_corte_estimada": 650 }, 
  { "curso": "Design de Moda", "nota_corte_estimada": 660 },
  { "curso": "Design Gráfico", "nota_corte_estimada": 680 },
  { "curso": "Direito", "nota_corte_estimada": 745 },
  { "curso": "Educação Física", "nota_corte_estimada": 610 },
  { "curso": "Enfermagem", "nota_corte_estimada": 705 },
  { "curso": "Engenharia Aeronáutica", "nota_corte_estimada": 790 },
  { "curso": "Engenharia Ambiental", "nota_corte_estimada": 680 },
  { "curso": "Engenharia Civil", "nota_corte_estimada": 710 },
  { "curso": "Engenharia da Computação", "nota_corte_estimada": 770 },
  { "curso": "Engenharia de Alimentos", "nota_corte_estimada": 660 },
  { "curso": "Engenharia de Controle e Automação", "nota_corte_estimada": 720 },
  { "curso": "Engenharia de Produção", "nota_corte_estimada": 710 },
  { "curso": "Engenharia Elétrica", "nota_corte_estimada": 715 },
  { "curso": "Engenharia Florestal", "nota_corte_estimada": 630 },
  { "curso": "Engenharia Mecânica", "nota_corte_estimada": 730 },
  { "curso": "Engenharia Mecatrônica", "nota_corte_estimada": 740 },
  { "curso": "Engenharia Química", "nota_corte_estimada": 725 },
  { "curso": "Estatística", "nota_corte_estimada": 690 },
  { "curso": "Farmácia", "nota_corte_estimada": 700 },
  { "curso": "Filosofia", "nota_corte_estimada": 610 },
  { "curso": "Física", "nota_corte_estimada": 660 },
  { "curso": "Fisioterapia", "nota_corte_estimada": 710 },
  { "curso": "Fonoaudiologia", "nota_corte_estimada": 690 },
  { "curso": "Gastronomia", "nota_corte_estimada": 640 },
  { "curso": "Geografia", "nota_corte_estimada": 610 },
  { "curso": "Geologia", "nota_corte_estimada": 660 },
  { "curso": "Gestão de Recursos Humanos", "nota_corte_estimada": 600 },
  { "curso": "História", "nota_corte_estimada": 630 },
  { "curso": "Informática Biomédica", "nota_corte_estimada": 710 },
  { "curso": "Jornalismo", "nota_corte_estimada": 690 },
  { "curso": "Letras - Português e Inglês", "nota_corte_estimada": 630 },
  { "curso": "Letras - Tradução", "nota_corte_estimada": 650 },
  { "curso": "Logística", "nota_corte_estimada": 590 },
  { "curso": "Marketing", "nota_corte_estimada": 630 },
  { "curso": "Matemática", "nota_corte_estimada": 650 },
  { "curso": "Medicina", "nota_corte_estimada": 810 },
  { "curso": "Medicina Veterinária", "nota_corte_estimada": 730 },
  { "curso": "Música", "nota_corte_estimada": 620 },
  { "curso": "Nutrição", "nota_corte_estimada": 700 },
  { "curso": "Odontologia", "nota_corte_estimada": 755 },
  { "curso": "Pedagogia", "nota_corte_estimada": 595 },
  { "curso": "Psicologia", "nota_corte_estimada": 740 },
  { "curso": "Publicidade e Propaganda", "nota_corte_estimada": 680 },
  { "curso": "Química", "nota_corte_estimada": 650 },
  { "curso": "Relações Internacionais", "nota_corte_estimada": 735 },
  { "curso": "Relações Públicas", "nota_corte_estimada": 660 },
  { "curso": "Serviço Social", "nota_corte_estimada": 610 },
  { "curso": "Sistemas de Informação", "nota_corte_estimada": 710 },
  { "curso": "Teatro", "nota_corte_estimada": 630 },
  { "curso": "Teologia", "nota_corte_estimada": 600 },
  { "curso": "Terapia Ocupacional", "nota_corte_estimada": 690 },
  { "curso": "Turismo", "nota_corte_estimada": 590 },
  { "curso": "Zootecnia", "nota_corte_estimada": 615 }
];

export const cursosGraduacao = cursosComNotas.map(c => c.curso);