
export const cursosGraduacao = [
    "Administração",
    "Agronomia",
    "Arqueologia",
    "Arquitetura e Urbanismo",
    "Artes Cênicas",
    "Artes Visuais",
    "Astronomia",
    "Biblioteconomia",
    "Biomedicina",
    "Ciência da Computação",
    "Ciências Biológicas",
    "Ciências Contábeis",
    "Ciências Econômicas",
    "Ciências Sociais",
    "Cinema e Audiovisual",
    "Dança",
    "Design",
    "Design de Interiores",
    "Design de Moda",
    "Design Gráfico",
    "Direito",
    "Educação Física",
    "Enfermagem",
    "Engenharia Aeronáutica",
    "Engenharia Ambiental",
    "Engenharia Civil",
    "Engenharia da Computação",
    "Engenharia de Alimentos",
    "Engenharia de Controle e Automação",
    "Engenharia de Produção",
    "Engenharia Elétrica",
    "Engenharia Florestal",
    "Engenharia Mecânica",
    "Engenharia Mecatrônica",
    "Engenharia Química",
    "Estatística",
    "Farmácia",
    "Filosofia",
    "Física",
    "Fisioterapia",
    "Fonoaudiologia",
    "Gastronomia",
    "Geografia",
    "Geologia",
    "Gestão de Recursos Humanos",
    "História",
    "Informática Biomédica",
    "Jornalismo",
    "Letras - Português e Inglês",
    "Letras - Tradução",
    "Logística",
    "Marketing",
    "Matemática",
    "Medicina",
    "Medicina Veterinária",
    "Música",
    "Nutrição",
    "Odontologia",
    "Pedagogia",
    "Psicologia",
    "Publicidade e Propaganda",
    "Química",
    "Relações Internacionais",
    "Relações Públicas",
    "Serviço Social",
    "Sistemas de Informação",
    "Teatro",
    "Teologia",
    "Terapia Ocupacional",
    "Turismo",
    "Zootecnia"
];
