export const temasRedacao = [
    { "tema": "2025: Perspectivas acerca do envelhecimento na sociedade brasileira"},
    { "tema": "2024: Desafios para a valorização da herança africana no Brasil" },
    { "tema": "2023: Desafios para o enfrentamento da invisibilidade do trabalho de cuidado realizado pela mulher no Brasil" },
    { "tema": "2022: Desafios para a valorização de comunidades e povos tradicionais no Brasil" },
    { "tema": "2021: Invisibilidade e registro civil: garantia de acesso à cidadania no Brasil" },
    { "tema": "2020: O estigma associado às doenças mentais na sociedade brasileira" },
    { "tema": "2019: Democratização do acesso ao cinema no Brasil" },
    { "tema": "2018: Manipulação do comportamento do usuário pelo controle de dados na internet" },
    { "tema": "2017: Desafios para a formação educacional de surdos no Brasil" },
    { "tema": "2016: Caminhos para combater a intolerância religiosa no Brasil" },
    { "tema": "2015: A persistência da violência contra a mulher na sociedade brasileira" },
    { "tema": "2014: Publicidade infantil em questão no Brasil" },
    { "tema": "2013: Efeitos da implantação da Lei Seca no Brasil" },
    { "tema": "2012: Movimento imigratório para o Brasil no século XXI" },
    { "tema": "2011: Viver em rede no século XXI: os limites entre o público e o privado" },
    { "tema": "2010: O trabalho na construção da dignidade humana" },
    { "tema": "2009: O indivíduo frente à ética nacional" },
    { "tema": "2008: Como preservar a floresta Amazônica: suspender a exploração ou encontrar alternativas sustentáveis?" },
    { "tema": "2007: O desafio de se conviver com as diferenças" },
    { "tema": "2006: O poder de transformação da leitura" },
    { "tema": "2005: O trabalho infantil na sociedade brasileira" },
    { "tema": "2004: Como garantir a liberdade de informação e evitar os abusos nos meios de comunicação" },
    { "tema": "2003: A violência na sociedade brasileira: como mudar as regras desse jogo" },
    { "tema": "2002: O direito de votar: como fazer dessa conquista um meio para promover as mudanças que o Brasil precisa?" },
    { "tema": "2001: Desenvolvimento e preservação ambiental: como conciliar os interesses em conflito?" },
    { "tema": "2000: Direitos da criança e do adolescente: como concretizar o que diz a lei" },
    { "tema": "1999: Cidadania e participação social" },
    { "tema": "1998: Viver e aprender" }
  ]